services:
    app:
        extends:
            file: common.yml
            service: app
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:14-bullseye
        env_file:
            - conf.env
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data: